function(IDL_GENERATE_SOURCE)
	cmake_parse_arguments(IDL_GENERATE_SOURCE
		"" "DESTINATION;IDLC_PATH" "INPUT" ${ARGN}
	)
	message(STATUS "DESTINATION ${IDL_GENERATE_SOURCE_DESTINATION}")
	message(STATUS "IDLC_PATH ${IDL_GENERATE_SOURCE_IDLC_PATH}")
	foreach(_INPUT ${IDL_GENERATE_SOURCE_INPUT})
		get_filename_component(_NAME ${_INPUT} NAME)
		string(LENGTH ${_NAME} _NAME_LEN)
		math(EXPR _NAME_LEN_NOEXT "${_NAME_LEN} - 4")
		string(SUBSTRING ${_NAME} 0 ${_NAME_LEN_NOEXT} _NAME)
		message(STATUS "INPUT NAME ${_NAME}")
	endforeach()
endfunction(IDL_GENERATE_SOURCE)
