function(IDL_GENERATE_SOURCE)
	cmake_parse_arguments(IDL_GENERATE_SOURCE
		"" "DESTINATION;IDLC_PATH;OUTPUT" "INPUT" ${ARGN}
	)
	message(STATUS "DESTINATION ${IDL_GENERATE_SOURCE_DESTINATION}")
	message(STATUS "IDLC_PATH ${IDL_GENERATE_SOURCE_IDLC_PATH}")
	file(GLOB_RECURSE _DEPS ${IDL_GENERATE_SOURCE_IDLC_PATH}/*.h ${IDL_GENERATE_SOURCE_IDLC_PATH}/*.cpp ${IDL_GENERATE_SOURCE_IDLC_PATH}/*.py)
	set(_OUTPUT)
	foreach(_INPUT ${IDL_GENERATE_SOURCE_INPUT})
		get_filename_component(_NAME ${_INPUT} NAME)
		string(LENGTH ${_NAME} _NAME_LEN)
		math(EXPR _NAME_LEN_NOEXT "${_NAME_LEN} - 4")
		string(SUBSTRING ${_NAME} 0 ${_NAME_LEN_NOEXT} _NAME)
		message(STATUS "INPUT NAME ${_NAME}")
		add_custom_command(OUTPUT
			${IDL_GENERATE_SOURCE_DESTINATION}/I${_NAME}.h
			${IDL_GENERATE_SOURCE_DESTINATION}/${_NAME}Remote.h
			${IDL_GENERATE_SOURCE_DESTINATION}/${_NAME}Remote.cpp
			DEPENDS ${_INPUT} ${_DEPS} ${IDL_GENERATE_SOURCE_IDLC_PATH}/idlc
			COMMAND ${IDL_GENERATE_SOURCE_IDLC_PATH}/idlc ${_INPUT} cpp ${IDL_GENERATE_SOURCE_DESTINATION}
			COMMENT "generating sources for ${_NAME}"
		)
		list(APPEND _OUTPUT ${IDL_GENERATE_SOURCE_DESTINATION}/${_NAME}Remote.cpp)
	endforeach()
	set(${IDL_GENERATE_SOURCE_OUTPUT} ${_OUTPUT} PARENT_SCOPE)
endfunction(IDL_GENERATE_SOURCE)
